[2025-03-24T12:04:18.887+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_service.ingest_new_data manual__2025-03-24T12:04:06.950635+00:00 [queued]>
[2025-03-24T12:04:18.896+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_service.ingest_new_data manual__2025-03-24T12:04:06.950635+00:00 [queued]>
[2025-03-24T12:04:18.897+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-24T12:04:18.912+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): ingest_new_data> on 2025-03-24 12:04:06.950635+00:00
[2025-03-24T12:04:18.921+0000] {standard_task_runner.py:60} INFO - Started process 1698 to run task
[2025-03-24T12:04:18.925+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_service', 'ingest_new_data', 'manual__2025-03-24T12:04:06.950635+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/data_service_dag.py', '--cfg-path', '/tmp/tmp631ttaai']
[2025-03-24T12:04:18.928+0000] {standard_task_runner.py:88} INFO - Job 67: Subtask ingest_new_data
[2025-03-24T12:04:18.943+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-24T12:04:18.985+0000] {task_command.py:423} INFO - Running <TaskInstance: data_service.ingest_new_data manual__2025-03-24T12:04:06.950635+00:00 [running]> on host 4d081b2ab468
[2025-03-24T12:04:19.071+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_service' AIRFLOW_CTX_TASK_ID='ingest_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T12:04:06.950635+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T12:04:06.950635+00:00'
[2025-03-24T12:04:19.129+0000] {docker.py:359} INFO - Starting docker container from image ingest_data:latest
[2025-03-24T12:04:19.144+0000] {docker.py:367} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-03-24T12:04:32.050+0000] {docker.py:429} INFO - no new data to add from data/new_data/weatherAU_scrapdata_test.csv
new data saved to current
new data saved to uptodate
[2025-03-24T12:04:32.769+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_service, task_id=ingest_new_data, execution_date=20250324T120406, start_date=20250324T120418, end_date=20250324T120432
[2025-03-24T12:04:32.841+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-24T12:04:32.877+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
